version: '3.8'

services:
  frontend:
    build: .
    container_name: crud-frontend-rwacof
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
