export const SET_PRODUCTS = 'SET_PRODUCTS';
export const OPEN_CREATE_MODAL = 'OPEN_CREATE_MODAL';
export const CLOSE_CREATE_MODAL = 'CLOSE_CREATE_MODAL';
export const OPEN_EDIT_MODAL = 'OPEN_EDIT_MODAL';
export const CLOSE_EDIT_MODAL = 'CLOSE_EDIT_MODAL';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const CLEAR_SELECTED_PRODUCT = 'CLEAR_SELECTED_PRODUCT';
export const SET_FORM_DATA = 'SET_FORM_DATA';
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA';
export const SET_ANALYTICS_DATA = 'SET_ANALYTICS_DATA';
export const SET_COMMODITY_TRENDS = 'SET_COMMODITY_TRENDS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';

